SELECT*
FROM [dbo].[Listing_Estimates]

SELECT*
FROM [dbo].[ebay May20-Apr21]

INSERT INTO Listing_Estimates (listing_title, year) VALUES
	('EMPTY LAND O LAKES BUTTER BOX with Indian Native American Discontinued Design', 2021),
	('Dynamite Magazine #46 1978 Kate Jackson 3-D Movies Charlies Angels VTG Sabrina', 2021),
	('Adventure Time Belt Buckle Seat Belt Click Style Black Puncha Yo Buns Unisex', 2021),
	('Johnny Mathis Complete Collection Classic Oldies Romance Hollywood 8 track tapes', 2021),
	('Vintage Disney Mary Poppins Read Along Story Book 1978 SEE HEAR READ', 2021),
	('Veggie Tales?BOB Tomato Kid Show Cap Mesh Back Baseball Hat Snapback Red Quirky', 2021),
	('Playskool Vintage 1983 muppets Stuffed Sesame Street Baby Big Bird Bonnet Diaper', 2021),
	('BUGS BUNNY Cadet Military Suffed Doll 14" Plush Looney Tunes Armed Forces Air', 2021),
	('Wonder Woman Plush Stuffed Cube Square pillow Justice League DC Comic Funko Pop', 2021),
	('VINTAGE POWDER JAR 1940s LUCIEN LELONG FACE BOX GLASS VANITY BATHROOM DECOR', 2021),
	('Denim & Supply Ralph Lauren Women Shirt Tunic Floral Print Blue White XS pleated', 2021),
	('Red Sweater Baby Boy 0 - 3 months Cable Knit Holiday Infant Christmas Cherokee', 2021),
	('BETTY BOOP Bifold Nylon Wallet OR souvenir pink coin purse PICK ONE', 2021),
	('Memorex DVD-R 50 Pack Spindle 16x 4.7GB 120 Minute New', 2021),
	('Rainforest Cafe Vintage 1999 Blue Yellow Coffee Mug Cup Set Excellent Condition', 2021),
	('Size 8 Timberland Brown Leather Hiking Boots Shoes Low Profile Women Rugged', 2021),
	('Lime Green Spacemaker Pencil Box Vintage Retro School Supplies Art Trinket', 2021),
	('Duck Dynasty Phil Robertson Talking Plush Teddy Bear 8 Beard Camo Headband toy', 2021),
	('Vintage Rubiks Race Game COMPLETE Ideal 1982 Rubiks Cube Fast Thinker Speed', 2021),
	('Microsoft Flight Simulator for Windows 95 PC Video Game Big Box 2', 2021),
	('CODi A02001 Laptop Notebook Computer Key Cable Lock One Key 6 ft Cord', 2021),
	('Ann Taylor Loft Size 8 Womens Jean Vest Denim Blue Button Cotton Distressed', 2021),
	('Large Big Bird Plush Toy Doll Sesame Street Applause Kids Vintage 1992 18 inch', 2021),
	('Vintage CASIO 64KB Digital Diary SF-8000 Business Organizer NEW Battery w/ cords', 2021),
	('Tamiflu XL Large Coffee Mug Cup Gift Pharmaceuticals Pharmacy Drug Rep Promo', 2021), 
	('Large Vintage LONDON FOG Sweater Mens Knit Acrylic Wool Blend Geometric 80s 90s', 2021),
	('Bird Kangaroo Bumble Bee Costume Halloween Pattern Simplicity 6671 Child 6 - 8', 2021),
	('Miller Lite Beer Keg Trucker Hat Cap Navy Blue Distressed Patch Alcohol Drinking', 2021),
	('Nike NFL Houston Texans #23 Football Jersey On Field Medium', 2021),
	('Vintage Kraft Teddy Bear Snowman Christmas Glass Jelly Jam Jar 1988 1992', 2021), 
	('Disney Sleeping Beauty Snow Globe Princess Aurora Dance With Owl Fairy Fairies', 2021), 
	('Vintage Stationary Card Box Green Floral Jewelry Drawers 70s Paper Pasteboard', 2021),
	('Care Bears Electronic Learning Game Toy Letter Memory Match ABC Alphabet Play', 2021) ,
	('Vintage Christmas Vest Tapestry Santa Claus Faces Ugly Tacky Party Medium Womens', 2021),
	('HALLMARK BROOSE THE MOOSE Plush 16" Floppy Stuffed Scarf Christmas Cabin Holiday', 2021),
	('Moose Stuffed Plush Animal 25 inch Big Large Brown Dan Dee Christmas Red Bow', 2021),
	('Le Chameau Womens US 6 EU 37 Marine Blue Saiga Lace up Rain Boots Wellies Rubber', 2021),
	('Vintage Disney World Milk Glass White Coffee Mug Cup Personalized Name Debbie', 2021),
	('Build A Bear BAB Workshop Red Sparkly Sequin Santa Hat Christmas Xmas', 2021), 
	('Vintage Anchor Hocking Fire King Oven Ware White D Handle Coffee Cup Mug', 2021),
	('Vintage Porcelain Coffee Cup Mug Japan Hippo Squirrel Duck Bird Colorful Pink', 2021),
	('Vtg 17" Ceramic & Cloth Old World SANTA CLAUS Figurine Doll Red Velvet Suit', 2021),     
	('Luminary Style 12 Days of Christmas Tree Tin Cut Punched Out Christmas Cheryls', 2021), 
	('Needlepoint Long Christmas Stocking Santa Claus Poinsettia Vintage Handmade 21', 2021),
	('Needlepoint Christmas Stocking Santa Claus Holly Old World Vintage Handmade 21', 2021),
	('1995 JC PENNEY Santa Checking His List  Norman Rockwell Christmas Ornament VTG', 2021),
	('Tommy Bahama Christmas Square Whiskey Glasses Double Old Fashioned Scotch Thick', 2021),
	('1981 Raggedy Ann Andy Arthur Vintage Collectible Pencil Unsharpened', 2021), 
	('Complete 8 Piece Mini Tea Set Christmas Santa Claus w/ Spoons Teapot Cream Plate', 2021),
	('Solid Brass Bronze Swan Swans Figurine Statues Decor SEI Taiwan Vintage Couple', 2021),
	('Lot 15 LARGE Real CLEAN Natural Pinecones Christmas Craft + Decoration Unscented', 2021),
	('Fox Racing Winter Coat Ski Jacket Faux Fur Hood Black Gray Head Print Mens Large', 2021),
	('Vintage Christmas Tree Skirt Puppy Puppies Dogs Canine Furry Tapestry Drum Gifts', 2021),
	('Villa Bacci Gold Christmas Tree Skirt 54 " Buttons Scalloped Red Fringe Heavy', 2021), 
	('Vintage 1995 Avon Santa Claus Christmas Stocking / Boots Large 29" Tall RARE', 2021),
	('Vintage Lipstick Lot Avon Estee Lauder Baby Blue Tubes Copper Penney Melba Stick', 2021),
	('Le Jardin de Max Factor EAU de Toilette Perfume Spray Women - 1 fl oz 80 full', 2021),
	('Disney Park Mickey Mouse 2008 Collectible 18" Disneyland Disneyworld New Years', 2021),
	('TUMI Mens Black Leather Belt ~ Gunmetal Buckle Size 48 / 120 Dress Golf 09 9109', 2021),
	('New Orleans Saints NFL Baby Toddler Football Team Jersey Outfit Jogger 12 Months', 2021),
	('Vintage Peanuts Camp Snoopy Collection Glass Cups Charlie Brown Lucy McDonalds', 2021),
	('Large Rocawear Mens Black Denim Jean Jacket Coat w/ Logo Spellout Heavy Durable', 2021),
	('Hallicrafters S-38D Tube Ham Radio Shortwave Receiver Tested and Working 1950s', 2021),
	('Mens 3XL Beretta Upland Shooting & Hunting Shirt With Game Pouch XXXL Vented', 2021), 
	('Womens Columbia Sz 8 Green Casual Cargo Hiking Shorts Travel Camping Long Length', 2021),
	('Large USA Made Vintage 90s LL L.L. Bean GOOSE DOWN Puffer Puffy Snap Vest Hiking', 2021),
	('Little Tikes Mini Playground Slide Vintage Dollhouse Size Furniture Toy', 2021),
	('Vintage Cotton Handmade Lace Crochet Doilies Heart Doily Valentine Red Napkin', 2021),
	('3 Vintage Retro Plastic Glass Collectible Ruby Red Restaurant Diner Cup Methods', 2021),
	('Baby Bop Vintage Barney The Purple Dinosaur Pillow w Carry Handle Large Stuffed', 2021),
	('Condor Tactical Breathable Flex Fitted Mesh Cap Hat w Hook and Loop Patch Space', 2021),
	('Pair Poly Resin & Wood Style Decorative Wall Shelves Sconces', 2021),
	('Vintage Complete FLINCH The Famous Card Game PARKER BROTHERS Salem Mass USA 1963', 2021),
	('Kohls GOLDFISH Plush Gold Fish The Fish with the Deep Sea Smile Stuffed', 2021),
	('Winking Smiling Smirking Kitty Cat Black White Figurine Wearing Green Sweater', 2021),
	('Vintage 1998 ZIGGY Have a Ziggyful Christmas Stuffed Plush Hanging Doll', 2021),
	('Tommy Hilfiger Blue Red Plaid Robe Bathrobe Belt Pockets Soft Plush Luxurious', 2021),
	('Woven Straw Boho Shoulder Cross Over Purse Bag Hippie Dyed Stripes Bohemian', 2021),
	('Cow Hair Cowhide Leather Overnight Small Duffel Bag Country Western Rancher VTG', 2021),
	('Saranac Cow Leather Fleece Fur Lined Navy Blue Winter Gloves Size Medium Vintage', 2021),
	('Imperial Orca Killer Whale 1989 Collectible Rubber Toy 11.5 From Sea World Vtg', 2021),
	('Hooters Golf Country Club Rare Hat Visor Cap Blue Orange Super Sports', 2021), 
	('Connecticut State Runners Mesh Trucker Hat Cap Snapback RunCT Running Run Blue', 2021), 
	('Pioneer Wear Vintage Southwestern Saddle Blanket Wool Blend Boho Aztec Size 8', 2021),
	('Vintage 90s Snow Ski Suit Toddler Size 2t 24 mos 80s Retro Embroidered Colorful', 2021),
	('Distressed Amethyst Denim Booty Jean Shorts Cutoffs Womens Size 3 Embellished', 2021), 
	('Texas Secede Invade 3XL T Shirt Trump Pride Yall are Lucky Secession Heavy Navy', 2021),
	('The Lucky Sew-It-Yourself Book Vintage Sewing Craft Learn Kids Pre-teen', 2021),
	('True Religion XXL Mens Plaid Cutoff Sleeves Distressed Fitted Shirt Pearl Snap', 2021),
	('Nike Under Armor Shorts Women Med Lot 2 Lined Running Athletic Gym Bright Colors', 2021),
	('I Love New York Hat Red Heart Big City Cap Pink NYC NY Travel I Heart Support', 2021),
	('Vogue Knitting Magazine 2018 Winter Krysten Ritter Jessica Jones Big Cozy Knits', 2021),
	('Disney Pooh Personalized Pillow Birth Keepsake Sealed Piglet Breezy Nursery', 2021),
	('Callaway Golf Womens Ladies Light Pink Hat Cap Rhinestones Black Mesh Adjustable', 2021),
	('Official Girl Scout Brownie Guide To Girl Scouting Binder', 2021),
	('L Saddlebrook Western Wear Blanket Jacket Southwest Aztec Ranchwear Ranch USA', 2021),
	('Vtg 1984 Bible Trivia Board Game Ultimate  #811 Cadaco 5400 Questions (Complete)', 2021),
	('2001 Nintendo GameCube Super Smash Bros Melee Mario Bros Complete', 2021),
	('Tales of Symphonia Nintendo Gamecube Video Game Complete Black Label gcn', 2021),
	('Metroid Prime Nintendo GameCube 2002 SAME DAY SHIP', 2021),
	('Metroid Prime 2: Echoes (Nintendo GameCube, 2004) Complete w/ Manual Black Label', 2021),
	('Dowdle Salt Lake City Temple Jigsaw Puzzle 500 pc Folk Art LDS Mormon 16 X 20', 2021), 
	('Donjoy Knee Brace Sleeve Hinged Support ACL MCL Size Medium 4 Strap', 2021), 
	('Blue Gray Plaid Wool Straight Short Skirt Talbots Lined Size 10 Ravenclaw', 2021),
	('Merona Womens One Piece Swimsuit Size 16W Black Maternity Pregnancy Rouche Skirt', 2021),
	('Bucilla Teapot Ornament Kit by Mary Engelbreit Felt Christmas Handmade #85018', 2021),
	('Anthropologie Marrakech Moto Black Jacket M Medium Assymetrical Stretchy', 2021), 
	('Ralph Lauren Plaid Check Short Sleeve Button Up Classic Fit Casual Shirt Mens L', 2021),
	('Mens 2XL Shirt Blue Pink Plaid Check Flannel Patch Marithe Francois Girbaud XXL', 2021),
	('Vintage Pocket Pass The Pigs Game - Never Played Complete - Milton Bradley', 2021),
	('Clairol True To Light LM-7 Lighted MakeUp Mirror Outlet Magnifying 4 Settings', 2021),
	('Pretty Pink K & Company Smash Folio Journal Scrapbook Book New NO Pen', 2021),
	('Vintage Comic Strip Cathy Guisewite Studio 1994 Cartoon Gift Bag Shopping 90s', 2021),
	('Vintage Little Tikes Cozy Coupe Dollhouse Mini Size 6" Car Red Yellow Miniature', 2021),
	('Me Reader Thomas The Train Storybook Replacement Reading Pad Blue Audio', 2021),
	('Renewing Minds Beginners Bible Nativity Replacement Figure Manger Creche for Kid', 2021),
	('Vintage Coca Cola Coke Soda Bottles Caps Wall Paper Border 4 Rolls New in Pkg', 2021),
	('Almost Famous Women Size 13 Jean Denim Booty Short Distressed Lace  Crochet Raw', 2021),
	('Wrangler Mens George Strait 4X Blue Plaid Cowboy Cut Western Ranch Shirt Roping', 2021),
	('Nabisco Barnums Circus Animal Crackers Cookie Tin 1989 Limited Edition', 2021),
	('Vintage Pan Am Airlines Flight Attendant Pilot Beige Canvas Tote Bag Fair Cond.', 2021),
	('Le Creuset Red Cast Iron Square Grill Pan Skillet Griddle No 26 Cherry Red', 2021),
	('Las Vegas Hard Rock Hotel Pink Taco Patch Mesh Cap Hat Dark Wash Jean Denim', 2021),
	('Vintage Arizona Colorblock Snapback Patched Smith Southwestern Velour Hat RARE', 2021),
	('Keepsake Cross Stitch Calendar w/ Charts Patterns Pillows 1998 Christmas Pumpkin', 2021),
	('December is for Christmas by Ann Scott - Wonder Books 1961 #776 Vintage Washable', 2021),
	('Rare Vintage Winnie the Pooh Wooden Blocks  w/ Carrier 5 Puzzles 16 Pc Complete', 2021),
	('Alfie the Christmas Tree by John Denver National Wildlife Federation Vtg Ranger', 2021),
	('THE ROBE by Lloyd C. Douglas- 1947 1953 60th Impress Illus. ed., Christian novel', 2021),
	('Nike Logo Featherlite Dri-Fit Blue Camo Running Baseball Hat Cap Ventilated', 2021),
	('Republic Patriotic Distressed Red Trump Stitched Baseball Cap Hat Ball Patch', 2021),
	('Pearl Snap Western Shirt Country Teal Blue Sz XL Fitted Legacy Falls Womens', 2021),
	('OMalleys Hollywood Beach Bar Florida Palm Tree Tank Top Shirt Mens Large VTG', 2021),
	('Lot Of 9 Boys Gerber Onesies Child of Mine Size Newborn & 0-3 month PERFECT COND', 2021),
	('4th of July Patriotic Flag Baby Boy Outfit Set Size 3 - 6 mos Cat & Jack Target', 2021),
	('Lot of 4 Outfits Baby Boy Clothes Sz 3 mos Carters Romper with and without Tags', 2021),
	('Vtg TableTop Finger Football Flick Redskins Superbowl xxxiii 33 Quarantine Games', 2021),
	('Lot of 2 Swaddle Me Wrap Sleep Sack Baby Size Sm/Md & Large Blanket Blue Fleece', 2021),
	('Gone With the Wind (DVD, 2009, 2-Disc Set, 70th Anniversary Edition)', 2021),
	('Gone With The Wind VHS Tape BANNED 1998  version Remastered Gold', 2021),
	('80s Vintage Reebok Classic hi High Top Aerobics RED leather RA801 freestyle 8.5', 2021),
	('LL BEAN Wicked Good Shearling Lined Suede Moccasin Slippers Womens 9 M Black', 2021), 
	('Barney BJ Use Your Imagination Interactive Board Book - 90s Sound Picture Keys', 2021),
	('Carhartt Bib Overalls Size 4T Toddler Girls Pink Jeans Lightweight Denim', 2021),
	('Playboy Bunny Pajama Pants Large Black Print Silky Bottoms has Pockets Elastic', 2021), 
	('Elmo Christmas Songs Board Book Music Sing Along Sesame Street New Batteries', 2021), 
	('Vintage Tractor Hat Roswell New Mexico Trucker Red Langford Work Equipment', 2021), 
	('TacoCat Spelled Backwards Shirt, Funny Taco Cat Lover Gift Baseball Tee Novelty', 2021),
	('David Brown California One Sz A Caftan MuuMuu Tropical Peacock Bright Vintage', 2021), 
	('EMPTY LAND O LAKES BUTTER BOX with Indian Native American Discontinued Design', 2021),
	('Disneys Pocahontas Play - a - Sound Interactive Good Used Condition 1995 Flit', 2021),
	('Harry Potter Slytherin Knit Scarf Soft Warm Thicken Green Costume USA seller', 2021),
	('Schutt Football Compression Set Youth Small Padded Shirt Shorts Black Protection', 2021),
	('Reebok Womens Warm Up Athletic Rain Jacket Black XL Full Zip Hooded Corded', 2021), 
	('EMPI EPIX XL Portable Tens Nerve Stimulator Transcutaneous UNIT ONLY Untested', 2021), 
	('Vintage Sony Sports Walkman SRF-85 AM/FM radio with belt clip', 2021),
	('Vintage Mid-century Modern Spartus Solid State Electric Plug-in Alarm Clock', 2021),
	('Taylor Swift RED CD New Sealed', 2021),
	('Vintage 1995 Warner Brothers Looney Tunes Wile E Coyote Road Runner Mouse Pad', 2021),
	('Vintage Coca Cola 1990s Christmas Dancing Animated Jazz Sax White Polar Bear', 2021),
	('Vintage WHITING & DAVIS Gold Mesh Purse Coin Cigarette Eye Glasses Case Clutch', 2021),
	('Reef Youth Boys Thongs Flip Flops Sandals Red / Black Size 6 / 7 Durable', 2021),
	('Vintage Perfumed Bath Powder Le Jardin De Max Factor Pink', 2021), 
	('Vintage Cartoon Network 1994 Pencil Box Made in USA', 2021),
	('Starbucks Clear Glass 16 Oz Pedestal Footed Coffee Latte Mug Cup Etched Logo', 2021),
	('Adidas Trefoil Firebird Velour Velvet Track Jacket Blue Small Full Zip Retro', 2021),
	('Disney Parks Mickey Halloween Pumpkin Popcorn Bucket Pail Candy Container Bowl', 2021),
	('Official Girl Scout Junior Guide To Girl Scouting Binder Purple Pink Book', 2021),
	('Little Girl Lot 3 Skirt Skort Carters 4T Pastel Ice Cream Pink Lavender Elastic', 2021), 
	('Wrangler Premium Red Buffalo Check Long Sleeve Plaid Fleece Shirt Jacket Size S', 2021),
	('Run Disney 2015 Marathon Weekend Track Running Jacket Womens Med Sparkly Glitter', 2021),
	('Prince Charming Handmade Royal Baby Costume Outfit 12 months', 2021), 
	('Fisher Price Crazy Combo Horn Trumpet Flute Kazoo Sax Kid Instrument Vintage', 2021),
	('Vintage LL Bean Night Shirt Plaid Flannel Sleeping Gown Women Large Red Winter', 2021),
	('Patagonia Rain Jacket Coat Gray Mens Medium Taped Seams Cinch Zip Wet Wear Vtg', 2021),
	('Vintage 80s National Logo Hat Hawaiian Tropical Print Snapback Trucker Cap', 2021), 
	('5 Panel Denim Jean Baseball Cap Hat USA Handmade ?', 2021), 
	('Vintage Betty Spaghetty Doll Original Style By Ohio Art Company NRFB', 2021),
	('Thomas Kinkade Dimensions 3D Puzzle Seaside Hideaway 300 pcs Sealed Cottage Sea', 2021),
	('Barney Purple Dinosaur Talking Plush Vtg 1993 Interactive Toy Lyons Group Tested', 2021),
	('Isotoner Genuine Leather Brown Mens Driving Gloves Cashmere Lined Medium', 2021),
	('Woolrich Mens XL Plaid Heavy Thick Long Sleeve Red Gray Button Down Flannel', 2021),
	('Orthanc Tower / Isengard 3D Puzzle (409 Pieces) Wrebbit - SEALED LOTR Lord Rings', 2021),
	('GIGO Doll - Bean Bag Vinyl Palm Pals Funny Expressions Faces Kids Baby Boy Hat', 2021),
	('Spiral Bound Green Hymn Book Chorister LDS Hardcover Leather Piano Music Mormon', 2021),
	('Vintage Walt Disney Mini Felt Christmas Stockings Santa Clause Pluto', 2021), 
	('DGK Skateboarding Large Tank Top Dirty Ghetto Kids Red Green Yellow Mens Street', 2021),
	('Pocket LDS Mormon Hymnal Hymns Scriptures Hymn Book Small Mini Black Missionary', 2021),
	('LDS Hymns 1985 First Print Pocket Edition Deseret Book Missionary Small Burgundy', 2021),
	('The Missionary Book of Inspirational Stories Quotes LDS Mormon Talk Lesson Ideas', 2021),
	('Coach Empty Brown Shoe Box Sun Damaged 9.5 Replacement', 2021), 
	('Tory Burch Empty Shoe Box Gift Storage Replacement Flat 9.5', 2021),
	('Torkel KORLING / WILD PLANTS IN FLOWERS THE PRAIRIE SWELL AND SWALE 1st Vintage', 2021), 
	('Blue Russia Russian Ski Beanie Cap Hat Fleece Lined Pom Pom Knit Snow', 2021), 
	('Thirty One Vary You Purple Quilted Circles Wallet Wristlet Organizer', 2021),
	('Vintage 1976 Mini Knickerbocker Raggedy Ann & Andy Small Cloth Dolls Stocking', 2021),
	('1970s Vintage Butterfly Knee Hi Socks Stockings Panty Hose Highpoint', 2021), 
	('Used Vintage 1997 ~ Yellow SKIP IT ~ Tiger Toys ? Counter works ~ Jump ~ankle', 2021),
	('1980s SKI Knit Black Sweater Currants By Jeri -Jo Disco Colors Size Med Vintage', 2021),
	('Rainforest Cafe Vintage Yellow Blue Coffee Mug Cup Excellent Condition 1999', 2021),
	('KISS 6 Tape Cassette Dynasty Love Gun Hotter Hell Dressed to Kill Rock 70s Music', 2021),
	('Renewing Minds Beginners Bible Nativity Replacement Figure Manger Creche for Kid', 2021),
	('Vintage Homco Gold Hummingbirds Wall Art Wall Decor Wall Hangings Mid Modern mcm', 2021),
	('Mickeys Christmas Carol Book 1984 First Trade Edition Walt Disney Vintage', 2021), 
	('Vintage 1985 BACK TO THE FUTURE Movie Soundtrack Cassette Tape Stuffer MCA', 2021),
	('Vintage 1985 BACK TO THE FUTURE Movie Soundtrack Cassette Tape Stuffer MCA', 2021),
	('Arizona Dancing Kokopelli Khaki Blue Jean Baseball Hat Cap Vintage Happy Hatter', 2021),
	('Vintage Clifford The Big Red Dog Puppy Cotton Jean Overalls Shorts Jumper 2T', 2021),
	('Yankee Candle Silver Red Hearts Vine Valentines Love Illuma Lid Topper Retired', 2021),
	('Vintage Glass McKee Roman Arch Red Salt Shaker Milk Glass Art Deco MCM', 2021),
	('Womens Duluth Trading Co Purple Plaid Nylon Vented Long Sleeve Shirt M Fitted', 2021),
	('Cowgirl Tuff Red Zip Up Hoodie Distressed Small Aztec Thunderbird Black Studs', 2021),
	('Enron Field Hat (circa 2000-2001) Vintage Bankrupt Enron Houston Astros', 2021),
	('Air Force One Presidential Crew Eagle Seal Baseball Cap Hat Vintage Weathered', 2021),
	('Vintage Sundyne Sunflo Pumps Compressors Trucker Snapback Hat Mesh Oil Gas', 2021),
	('Dodge Ram Truck Suede-like Hat Cap Paper Straw Trucker Western Patch Mesh Weave', 2021),
	('Hasbro Softies Muppet Babies Fozzie Bear Plush Stuffed Animal Vintage 1983', 2021),
	('New Vintage 1997 Baby Looney Tunes Magnetic Picture Frames Tweety Bird Sylvester', 2021);